debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org:
      springframework.web.servlet: debug
      hibernate:
        sql: debug
        type.descriptor.sql.BasicBinder: trace
        orm.jdbc.bind: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: edwin
    password: edwin
    dirver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
  sql.init.mode: always

---

#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#
#  test.database.replace: none


